### ISSUE TITLE
Q: custom JSON response with data for form "options"

### ISSUE THREAD

**Issue by matissg** [brolycjw/datatable#2]
Hi,
First of all looks like you have nice gem for Datatables and I'd like to try it out.
I was wondering would it be possible to have JSON response like this?
```
{
    "data": [{
        "id": 3,
        "name": "some name here",
        "statuses": [{
            "value":  "planning",
            "label": "In planning"
        }]
    }],
    "options": {
        "statuses[].id": [{
            "value": "planning",
            "label": "In planning"
        }, {
            "value": "active",
            "label": "Active"
        }]
    }
}
```
I'm using Editor Datatables and would need to get back something like this in order to have my drop-down options populated correctly in my form. In my table I would have column named "Status" and value in view would be "In planning". In my form I would have field "Status" with values from `"statuses[].id"`, where my value would be selected. This is done by Editor Datatables if I pass JSON as shown above.

In my app I get `status` as this array of arrays
```
status = [
   ["Deleted", "deleted", 0],
   ["In planning", "planning", 1],
   ["In approval", "approval", 2]
]
```
and can transform it to array of hashes with
`status.map { |s| {label: s[0], value: s[1]} }`

So far I'm thinking I could get this by tweaking these lines from your example:
```
column(:statuses, header: "Status") do |user|
   user.status
end
```
I'm not sure if this ir correct way to do + how can I pass that `"statuses[].id"` as options?
I'd be happy for any help. Thank you.

**Comment by brolycjw** [comment]
Hi, matissg! Thanks for the interest in trying out my gem. I have not used Editor Datatables since it is proprietary but I will do what I can to help out with your issue. Currently, you can override the as_json method in your Datatable class to modify the json however you please. In your case, you can do this:

```ruby
# app/datatables/proposal_datatable.rb

class ProposalDatatable
  include Datatable

  scope { Proposal }

  column(:statuses, header: 'Status') do |proposal|
    proposal.status.map { |s| { label: s[0], value: s[1] }
  end

  # super contains the original json hash, so simply merge it with your custom options


  def as_json(_options)
    old_json = super
    options = old_json[:data].map do |proposal|
      'statuses[].id': [{
        value: proposal[:statuses][:value],
        label: proposal[:statuses][:label]
      }, {
        value: proposal[:statuses][:value],
        label: proposal[:statuses][:label]
      }]
    end
    old_json.merge(options: options)
  end
end
```

**Comment by matissg** [comment]
@brolycjw  Thank you, this helps. In my specific case I could inject `options` with this one:
```
  def as_json(_options)
    old_json = super
    statuses = Campaign::Campaign.translated_statuses
    options = { options: {
        "statuses[].id": statuses.map { |s| {value: s[1], label: s[0]} }
      }}
    old_json.merge(options: options)
  end 
```

I have few more questions:
1) how do you pass options to your datatable? for example, `current_user` to do `current_user.proposals` in `scope`?
2) would it be possible to create JSON response like this?
```
{
    "DT_RowId": "row_1",
    "users": {
        "first_name": "Quynn",
        "last_name": "Contreras",
        "site": "1"
    },
    "sites": {
        "name": "Edinburgh"
    },
    "user_dept": {
        "dept_id": "1"
    },
    "dept": {
        "name": "IT"
    }
}
```
Basically it's a bit more than just returning back values from columns in table. [More here](https://editor.datatables.net/examples/advanced/joinLinkTable.html).

**Comment by brolycjw** [comment]
Hi matissg, I am not sure I understand your first question. You can define any initial scope you wish with the scope api, and datatable will use that scope. What is it that you wish to achieve?
2. You may use the results method directly in this case to obtain the resulting model objects and use them to customize your json response.

```ruby
class UsersDatatable
  include Datatable

  scope { User.includes(:sites, :user_dept, :dept) }

  column :name

  order_by :name, 'desc'

  # #results method contains the resulting scope i.e. collection of User objects
  def as_json
    new_data = results.each_with_index.map do |user, i|
      {
        DT_RowId: "row_#{i}",
        users: { first_name: user.first_name,
                 last_name: user.last_name,
                 site: user.site.id },
        sites: { name: user.site.name },
        user_dept: { dept_id: user.user_dept },
        dept: { name: 'IT' }
      }
    end
    super.merge(data: new_data)
  end
end
```

**Comment by matissg** [comment]
@brolycjw  Thank you for explaining. As I understand, it's just I'm creating scopes in my models and then use them in my `datatable` class, right?
It seems your gem is more flexible than [ajax-datatables-rails](https://github.com/jbox-web/ajax-datatables-rails) which I'm using now. The thing I will need is to get association records for `current_user`. At the moment in my controller I have:
```
  def index
    campaigns = Campaign::CampaignDatatable.new(
      view_context, { user: current_user }
    )
    respond_with campaigns
  end
```
then in my `campaign_datatable.rb` I can get records like this:
```
  def user
    @user ||= options[:user]
  end

  def get_raw_records
    user.campaigns.order("date_trunc('day', updated_at) DESC")
  end
```
I can access my `current_user` and get `campaigns` for that. **What would be your suggestion to access `current_user` in your gem, please?**
I could fetch `current_user` in Model [with something like this](https://amitrmohanty.wordpress.com/2014/01/20/how-to-get-current_user-in-model-and-observer-rails/), however not sure if this is the right way.

**Comment by brolycjw** [comment]
Hi matissg, the datatable is being initialized with the view_context of the controller, so you have access to the current_user from within the datatable scope.

```ruby
class UsersDatatable
  include Datatable

  # scope has access to controller view context so
  # you may call current_user from within it
  scope do
    current_user.campaigns
  end

  column :name

  order_by :updated_at, 'desc'
end
```

**Comment by matissg** [comment]
@brolycjw Great! IMHO people would find your gem flexible and easy to use if you added some of these examples in your readme section. In addition as I understand you have even added some View part in order to easily render DataTable without big JS modification. Although it's not my case, it could be helpful for someone.
Once again - thank you for clearing out. I'll play a bit more with your gem and let's see how it goes. So far it seems exactly what I need 👍

**Comment by brolycjw** [comment]
@matissg glad to hear it fits your requirements so far. My team is already using this gem in various projects, and some of the existing features were built based their project requirements. Feel free to suggest new features or even better, submit a pull request so the gem could be improved further.

**Comment by matissg** [comment]
@brolycjw  I'm sorry, but it seems I can't access my `current_user` in datatable.
In my controller I have this:
```
  def index
    campaigns = Campaign::CampaignDatatable.new(view_context)
    respond_with campaigns
  end
```
then in datatable I have this scope:
```
  scope do
    current_user.campaigns.order("date_trunc('day', updated_at) DESC")
  end
```
and I get this error: `NameError (undefined local variable or method "current_user"`
`current_user` is defined in my `SessionsHelper` 
**What am I doing wrong here, please?**
In my console I can do `user=User.first` and then `user.campaigns`
I checked I can get all records by `Campaign::Campaign.order("date_trunc('day', updated_at) DESC")` in my scope so in general datatable works.

**Comment by brolycjw** [comment]
@matissg There is a bug in the current version which I will fix in the coming week. In the meantime, you can workaround this issue by adding this line.

```ruby
class CampaignDatatable
  # add this line
  delegate :current_user, to: :@view

  scope { current_user.campaigns.order("date_trunc('day', updated_at) DESC") }
end
```

Also, appreciate if you can create a new issue, so I can reference it once it is fixed.
