### ISSUE TITLE
Can't access controller variables in datatable

### ISSUE THREAD

**Issue by matissg** [brolycjw/datatable#4]
It seems I can't access my `current_user` in datatable scope.
`current_user` is defined in my SessionsHelper and in my controller I have this:

```
  def index
    campaigns = Campaign::CampaignDatatable.new(view_context)
    respond_with campaigns
  end
```
then in datatable I have this scope:

```
  scope do
    current_user.campaigns.order("date_trunc('day', updated_at) DESC")
  end
```
and I get this error: `NameError (undefined local variable or method "current_user"`
In my console I can do `user=User.first` and then `user.campaigns`
I checked I can get all records by `Campaign::Campaign.order("date_trunc('day', updated_at) DESC")` in my scope so in general datatable works.

In addition I may need to do `@company = Company.first` in controller and then in datatable:
```
  scope do
    @company.campaigns.order("date_trunc('day', updated_at) DESC")
  end
```

**Comment by brolycjw** [comment]
To be fixed in next release.
